In [5]:
import pandas as pd

## import data

In [8]:
cancer_deaths = pd.read_csv('./data/Hospice_General_Information.csv')

## find TN

In [20]:
tn_cancer_deaths = cancer_deaths[cancer_deaths['State'] == 'TN']
tn_cancer_deaths.head()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,PhoneNumber,CMS Region,Ownership Type,Certification Date
2889,441501,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NaN,NASHVILLE,TN,37203,Davidson,(615) 327-1085,4,Non-Profit,04/10/1984
2890,441502,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",NaN,MEMPHIS,TN,38134,Shelby,(901) 516-1600,4,Non-Profit,08/31/1984
2891,441504,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,NaN,CHATTANOOGA,TN,37416,Hamilton,(423) 892-4289,4,Non-Profit,06/30/1986
2892,441506,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,NaN,BARTLETT,TN,38134,Shelby,(901) 680-0378,4,For-Profit,02/09/1987
2893,441507,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,NaN,SPRINGFIELD,TN,37172,Robertson,(615) 384-9425,4,Other,07/13/1987

## subset columns and make column case smaller

In [24]:
tn_cancer_deaths = tn_cancer_deaths[['Facility Name', 'Address Line 1', 'City', 'State', 
                                     'County Name', 'CMS Region', 'Ownership Type', 'Certification Date']]
tn_cancer_deaths.head()

,Facility Name,Address Line 1,City,State,County Name,CMS Region,Ownership Type,Certification Date
2889,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NASHVILLE,TN,Davidson,4,Non-Profit,04/10/1984
2890,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",MEMPHIS,TN,Shelby,4,Non-Profit,08/31/1984
2891,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,CHATTANOOGA,TN,Hamilton,4,Non-Profit,06/30/1986
2892,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,BARTLETT,TN,Shelby,4,For-Profit,02/09/1987
2893,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,SPRINGFIELD,TN,Robertson,4,Other,07/13/1987

In [26]:
tn_cancer_deaths.columns = tn_cancer_deaths.columns.str.lower()
tn_cancer_deaths.head()

,facility name,address line 1,city,state,county name,cms region,ownership type,certification date
2889,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NASHVILLE,TN,Davidson,4,Non-Profit,04/10/1984
2890,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",MEMPHIS,TN,Shelby,4,Non-Profit,08/31/1984
2891,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,CHATTANOOGA,TN,Hamilton,4,Non-Profit,06/30/1986
2892,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,BARTLETT,TN,Shelby,4,For-Profit,02/09/1987
2893,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,SPRINGFIELD,TN,Robertson,4,Other,07/13/1987

## examine head and tail of TN data; print dimensions of data

In [27]:
tn_cancer_deaths.head()

,facility name,address line 1,city,state,county name,cms region,ownership type,certification date
2889,ALIVE HOSPICE INC,1718 PATTERSON ROAD,NASHVILLE,TN,Davidson,4,Non-Profit,04/10/1984
2890,METHODIST ALLIANCE HOSPICE,"6400 SHELBY VIEW DRIVE, SUITE 101",MEMPHIS,TN,Shelby,4,Non-Profit,08/31/1984
2891,HOSPICE OF CHATTANOOGA INC,4411 OAKWOOD DRIVE,CHATTANOOGA,TN,Hamilton,4,Non-Profit,06/30/1986
2892,AMEDISYS HOSPICE CARE,6570 STAGE ROAD SUITE 110,BARTLETT,TN,Shelby,4,For-Profit,02/09/1987
2893,NORTHCREST HOME HEALTH AND HOSPICE,212 NORTHCREST DRIVE,SPRINGFIELD,TN,Robertson,4,Other,07/13/1987

In [28]:
tn_cancer_deaths.tail()

,facility name,address line 1,city,state,county name,cms region,ownership type,certification date
2940,ENCOMPASS HOSPICE OF TENNESSEE,828 ROYAL PARKWAY SUITE 113,NASHVILLE,TN,Davidson,4,For-Profit,06/16/2010
2941,QUALITY HOSPICE,341 WEST CENTRAL AVENUE,JAMESTOWN,TN,Fentress,4,For-Profit,01/04/2013
2942,HEARTH HOSPICE,1800A ROSSVILLE AVE SUITE 114,CHATTANOOGA,TN,Hamilton,4,For-Profit,03/22/2013
2943,"AMEDISYS HOSPICE, AN ADVENTA COMPANY",400 ROYAL PARKWAY,NASHVILLE,TN,Davidson,4,Other,01/05/2016
2944,KINDRED HOSPICE,"430 STUART RD NE, STE 2",CLEVELAND,TN,Bradley,4,For-Profit,01/04/2017

In [31]:
print('there are ' + str(tn_cancer_deaths.shape[0]) + ' cancer centers in TN')

there are 56 cancer centers in TN